from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie


class MyMainWindow(object):
    def setupUi(self, Window):
        Window.setObjectName("MainWindow")
        Window.resize(314, 462)
        Window.setStyleSheet("background-color: #b9b8b8;")
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")

        # self.helloSlogan = QtWidgets.QLabel(self.centralwidget)
        # self.helloSlogan.setGeometry(QtCore.QRect(70, 160, 161, 21))

        # self.helloSlogan.setFont(font)
        # self.helloSlogan.setWordWrap(True)
        # self.helloSlogan.setObjectName("label")
        # self.helloSlogan.setStyleSheet("color: rgb(0, 117, 210);")
        # self.normalizeLabel('helloSlogan')
        # font = QtGui.QFont()
        # font.setFamily("Calibri")
        # font.setPointSize(14)
        # font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        # self.helloSlogan.setFont(font)
        # self.helloSlogan.setGeometry(QtCore.QRect(70, 160, 161, 21))
        # self.helloSlogan.setTextFormat(QtCore.Qt.AutoText)
        self.helloSlogan = QtWidgets.QLabel(self.centralwidget)
        self.helloSlogan.setGeometry(QtCore.QRect(70, 160, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.helloSlogan.setFont(font)
        self.helloSlogan.setStyleSheet("color: rgb(0, 117, 210);")
        self.helloSlogan.setTextFormat(QtCore.Qt.AutoText)
        self.helloSlogan.setWordWrap(True)
        self.helloSlogan.setObjectName("helloSlogan")
        # self.func1 = QtWidgets.QLabel(self.centralwidget)
        # self.normalizeLabel('func1')
        # font = QtGui.QFont()
        # font.setFamily("Calibri")
        # font.setPointSize(14)
        # self.func1.setFont(font)
        # self.func1.setStyleSheet("color: rgb(0, 117, 210);")
        # self.func1.setWordWrap(True)
        # self.func1.setObjectName("label_3")
        self.normalizeLabel('func1')
        self.func1.setGeometry(QtCore.QRect(60, 280, 201, 51))

        # self.instruction = QtWidgets.QLabel(self.centralwidget)
        # font = QtGui.QFont()
        # font.setFamily("Calibri")
        # font.setPointSize(14)
        # self.instruction.setFont(font)
        # self.instruction.setStyleSheet("color: rgb(0, 117, 210);")
        # self.instruction.setWordWrap(True)
        # self.instruction.setObjectName("label_2")
        self.normalizeLabel('instruction')
        self.instruction.setGeometry(QtCore.QRect(60, 250, 201, 21))


        self.voiceFig = QtWidgets.QLabel(self.centralwidget)
        self.voiceFig.setGeometry(QtCore.QRect(70, 50, 161, 121))
        self.voiceFig.setText("")
        self.gif = QMovie("icon/voice.gif")
        self.voiceFig.setMovie(self.gif)
        self.gif.start()
        self.voiceFig.setScaledContents(True)
        self.voiceFig.setObjectName("voiceFig")

        # self.func2 = QtWidgets.QLabel(self.centralwidget)
        # self.func2.setGeometry(QtCore.QRect(60, 330, 201, 51))
        # font = QtGui.QFont()
        # font.setFamily("Calibri")
        # font.setPointSize(14)
        # self.func2.setFont(font)
        # self.func2.setStyleSheet("color: rgb(0, 117, 210);")
        # self.func2.setWordWrap(True)
        # self.func2.setObjectName("label_4")
        self.normalizeLabel('func2')
        self.func2.setGeometry(QtCore.QRect(60, 330, 201, 51))

        Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Window)
        self.statusbar.setObjectName("statusbar")
        Window.setStatusBar(self.statusbar)

        print(self.func1)
        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voice Assistant"))
        self.helloSlogan.setText(_translate("MainWindow", "Hi! How can I help?"))
        self.instruction.setText(_translate("MainWindow", "You can:"))
        self.func1.setText(_translate("MainWindow", "1. Enjoy music by saying \"Play music\""))
        self.func2.setText(_translate("MainWindow", "2. Take some notes by saying \"Open Notepad\""))

    def normalizeLabel(self, name):
        self.__setattr__(name, QtWidgets.QLabel(self.centralwidget))
        label = self.__getattribute__(name)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        label.setFont(font)
        label.setStyleSheet("color: rgb(0, 117, 210);")
        label.setWordWrap(True)
        label.setObjectName(name)
